### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by qingchenkanlu** [zhanhz/KRF#1]
感谢分享，代码里面https://github.com/zhanhz/KRF/blob/a85affce29792163aa8904d1c826cd165629ff7d/krf/generate_color_pts.py#L27

xyzrgb.obj似乎不在YCB-V数据集中，它是如何生成或是哪里下载的？可以提供一下吗，谢谢！

**Comment by zhanhz** [comment]
谢谢你提醒了我，这个你可以用数据集里的texture.obj，用meshlab把纹理颜色信息加到点云上。我之后会重新打包一份到网盘里。

**Comment by qingchenkanlu** [comment]
好的，非常感谢

**Comment by qingchenkanlu** [comment]
不好意思，我在测试LM数据集的时候，发现数据集还少了图片
FileNotFoundError: [Errno 2] No such file or directory: '/media/yusheng/F/code/KRF-main/krf/datasets/linemod/Linemod_preprocessed/data/01/add_data/pred_label/0960.png'
麻烦您再确认一下，万分感谢！

**Comment by zhanhz** [comment]
你好，我印象中应该没有用LineMOD原始数据作为测试集，应该不会报这个错误，因为先前工作中这个数据集的准确率已经非常高了。不过没关系，我已经把你提到的缺失的数据都上传了。如果还有问题，欢迎继续交流。

**Comment by qingchenkanlu** [comment]
感谢，但是我在运行程序的时候还遇到了一些bug
yusheng@yusheng:~/code/KRF/krf$ sh generate_ds.sh 
test_dataset_size:  2949
loading resnet34 pretrained mdl.
==> Loading from checkpoint 'train_log/ycb/checkpoints/FFB6D_best.pth.tar'
==> Done
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/yusheng/F/code/KRF-main/krf/generate_ds.py", line 235, in <module>
    main()
  File "/media/yusheng/F/code/KRF-main/krf/generate_ds.py", line 231, in main
    cal_view_pred_pose(model, data, epoch=i, obj_id=obj_id)
  File "/media/yusheng/F/code/KRF-main/krf/generate_ds.py", line 150, in cal_view_pred_pose
    if data['rnd_typ'][0] =='render':
KeyError: 'rnd_typ'

yusheng@yusheng:~/code/KRF/krf$ sh generate_ds.sh 
test_dataset_size:  2949
loading resnet34 pretrained mdl.
==> Loading from checkpoint 'train_log/ycb/checkpoints/FFB6D_best.pth.tar'
==> Done
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/yusheng/F/code/KRF-main/krf/generate_ds.py", line 238, in <module>
    main()
  File "/media/yusheng/F/code/KRF-main/krf/generate_ds.py", line 234, in main
    cal_view_pred_pose(model, data, epoch=i, obj_id=obj_id)
  File "/media/yusheng/F/code/KRF-main/krf/generate_ds.py", line 190, in cal_view_pred_pose
    ensure_fd(os.path.join(root, data['name'][0][:-6]))
KeyError: 'name'


是不是还有其他的一些数据处理？

**Comment by zhanhz** [comment]
之前这一行被注释掉了，现在没问题了。如果之后打算重新训练baseline (FFB6D)的话可能需要用到这个数据集，要是有问题的话重新注释掉就行。
https://github.com/zhanhz/KRF/blob/e3b651443943d481215abf4ac50739d6831f9467/krf/datasets/ycb/ycb_dataset.py#L346

**Comment by qingchenkanlu** [comment]
好的，非常感谢你的回答
