### ISSUE TITLE
KeyError: 'rgb'

### ISSUE THREAD

**Issue by d-serafly** [zhanhz/KRF#3]
不好意思又来打扰了0.0，复现LM的ape数据集时，训练完一个epoch后，val: 18it，报了一个“KeyError: 'rgb'”的错误。
val: 17it [00:07,  4.07it/s]
val: 18it [00:08,  2.52it/s]
ape_epochs:   3%|        | 1/30 [00:42<20:38, 42.71s/it]
Traceback (most recent call last):
  File "/home/extend/KRF/krf/train_lm_refine_pcn.py", line 622, in <module>
    train()
  File "/home/extend/KRF/krf/train_lm_refine_pcn.py", line 613, in train
    clr_div=clr_div
  File "/home/extend/KRF/krf/train_lm_refine_pcn.py", line 440, in train
    val_loss = self.eval_epoch(test_loader)
  File "/home/extend/KRF/krf/train_lm_refine_pcn.py", line 330, in eval_epoch
    _, loss, eval_res = self.model_fn(self.model, data, is_eval=True)
  File "/home/extend/KRF/krf/train_lm_refine_pcn.py", line 241, in model_fn
    end_points = model(cu_dt)
  File "/home/extend/miniconda3/envs/KRF/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/extend/miniconda3/envs/KRF/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/extend/miniconda3/envs/KRF/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/extend/miniconda3/envs/KRF/lib/python3.6/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/extend/KRF/krf/models/ffb6d_refine_pcn.py", line 216, in forward
    rgb_emb = self.cnn_pre_stages(inputs['rgb'])  # stride = 2, [bs, c, 240, 320]
KeyError: 'rgb'
我DEBUG检查了一下上面Traceback下的代码，没有发现问题，ToT

**Comment by zhanhz** [comment]
只有这个iter有问题吗？看起来挺奇怪的，因为它通过了最开始100iter后的测试。最好能定位一下是哪个文件的问题。

**Comment by d-serafly** [comment]
> 只有这个iter有问题吗？看起来挺奇怪的，因为它通过了最开始100iter后的测试。最好能定位一下是哪个文件的问题。

不固定iter，基本是在val:20it左右的时候抛出这个错误。应该不是数据的问题，因为我使用FFB6D的代码可以正常运行。

**Comment by d-serafly** [comment]
切换成cat或者duck数据集都完成了一轮测试，重新切换成ape以后还是存在这个问题，这次是第70iter左右。是不是存在某张图计算出错的情况？

**Comment by zhanhz** [comment]
我在本地测试过跑完整个训练流程都是没有问题的，你看下出现问题时“go”键值是否为true。如果是数据的问题，只有读入数据为空时才可能会出现KeyError: 'rgb'，但这时“go”应该是false了。
另外，你在开始训练后的100iter时应该跑过一次val吧？那时没有问题吗？

**Comment by d-serafly** [comment]
好的，感谢解答！通过了！

**Comment by zhanhz** [comment]
> 好的，感谢解答！通过了！
我可以了解一下是什么原因吗？方便我后续的一些改进
